name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Based on your @types/node version

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Generate migrations
      run: npm run migration:generate
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Run migrations
      run: npm run migration:run
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # Add any other necessary environment variables
    - name: Deploy to production
      run: |
        echo "Add your deployment commands here"
        # For example:
        # - ssh into your server
        # - copy the dist folder
        # - restart your Node.js application
      env:
        # Add any necessary deployment environment variables
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
