name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Check formatting
      run: npm run format:check
    - name: Build
      run: npm run build
    - name: Generate migrations
      run: npm run migration:generate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run migrations
      run: npm run migration:run
      env:
        # Add any necessary environment variables for database connection
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Deploy to production
      # Add your deployment steps here
      run: |
        echo "Add your deployment commands here"
        # For example:
        # - ssh into your server
        # - pull the latest changes
        # - restart your Node.js application