name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'production' || 'development' }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_TYPE: ${{ secrets.DB_TYPE }}
      REFRESH_TOKEN_SECRET_KEY: ${{ secrets.REFRESH_TOKEN_SECRET_KEY }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      JWKS_URI: ${{ secrets.JWKS_URI }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}
      REFRESH_TOKEN_EXPIRE: ${{ secrets.REFRESH_TOKEN_EXPIRE }}
      SONAR_CLOUD_PASSWORD: ${{ secrets.SONAR_CLOUD_PASSWORD }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run migrations
      run: npm run migration:run 

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Use Node.js 18.x
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 18.x
  #       cache: 'npm'
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: dist
  #       path: dist
  #   - name: Run migrations
  #     run: npm run migration:run
  #     env:
  #       DATABASE_URL: ${{ secrets.DATABASE_URL }}
  #   - name: Build and push Docker image
  #     env:
  #       DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  #       DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  #     run: |
  #       docker build -t your-dockerhub-username/your-repo-name:${{ github.sha }} .
  #       echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  #       docker push your-dockerhub-username/your-repo-name:${{ github.sha }}
  #   - name: Deploy to production
  #     run: |
  #       echo "Add your deployment commands here"
  #       # For example:
  #       # - ssh into your server
  #       # - pull the latest Docker image
  #       # - stop the old container and start a new one
  #     env:
  #       DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}