name: Node.js CD

on:
  workflow_call:

jobs:
  build-and-push-to-docker:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ajay980p/auth_service
      IMAGE_TAG: build-${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}